#!/usr/bin/env python3
"""
deploy.py — LoopLab Auto-Research Pipeline Step 4
Generate GitHub Actions workflow to auto-deploy challenger variants.
Also creates the deployment manifest and variant index page.
"""

import json
import os
from datetime import datetime
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
VARIANTS_DIR = Path(__file__).parent / "variants"
REPO_ROOT = Path(__file__).parent.parent  # assumes auto-research/ is inside repo

GITHUB_REPO = os.environ.get("GITHUB_REPO", "kalawcreator919/couponsnap-landing")
GITHUB_PAGES_BASE = f"https://{GITHUB_REPO.split('/')[0]}.github.io/{GITHUB_REPO.split('/')[1]}"


def load_variants_summary() -> dict:
    summary_file = DATA_DIR / "variants_summary.json"
    if not summary_file.exists():
        raise FileNotFoundError("variants_summary.json not found. Run generate.py first.")
    with open(summary_file, encoding="utf-8") as f:
        return json.load(f)


def generate_github_actions_workflow(variants: list) -> str:
    """Generate GitHub Actions workflow YAML for deploying variants."""
    variant_deploy_steps = ""
    for v in variants:
        vtype = v["variant_type"]
        variant_deploy_steps += f"""
      - name: Deploy variant-{vtype}
        run: |
          mkdir -p challengers/{vtype}
          cp auto-research/variants/variant_{vtype}.html challengers/{vtype}/index.html
          echo "Deployed variant-{vtype}"
"""

    return f"""# Auto-generated by LoopLab Auto-Research Pipeline
# DO NOT EDIT MANUALLY - regenerated on each pipeline run
name: Deploy CRO Challengers

on:
  workflow_dispatch:
    inputs:
      run_pipeline:
        description: 'Run full pipeline before deploying'
        required: false
        default: 'false'
  push:
    branches: [main]
    paths:
      - 'auto-research/variants/**'
      - '.github/workflows/deploy-challengers.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-challengers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run pipeline (if requested)
        if: github.event.inputs.run_pipeline == 'true'
        env:
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          GA4_PROPERTY_ID: ${{{{ secrets.GA4_PROPERTY_ID }}}}
          GA4_CREDENTIALS: ${{{{ secrets.GA4_CREDENTIALS }}}}
        run: |
          cd auto-research
          python harvest.py
          python evaluate.py
          python generate.py
          python deploy.py
{variant_deploy_steps}
      - name: Copy variant manifests
        run: |
          cp auto-research/data/variants_summary.json challengers/manifest.json

      - name: Generate variant index
        run: |
          python auto-research/deploy.py --generate-index

      - name: Commit and push challengers
        run: |
          git config user.name "LoopLab AutoResearch Bot"
          git config user.email "noreply@looplab.ai"
          git add challengers/
          git diff --cached --quiet || git commit -m "chore: deploy CRO challengers [$(date -u +%Y-%m-%d)]

Co-Authored-By: Paperclip <noreply@paperclip.ing>"
          git push

  verify-deployment:
    needs: deploy-challengers
    runs-on: ubuntu-latest
    steps:
      - name: Wait for GitHub Pages
        run: sleep 30

      - name: Verify variant pages
        run: |
          for variant in headline cta layout; do
            url="{GITHUB_PAGES_BASE}/challengers/$variant/"
            status=$(curl -sk -o /dev/null -w "%{{http_code}}" "$url")
            echo "variant-$variant: HTTP $status"
            [ "$status" = "200" ] || echo "WARNING: $variant returned $status"
          done
"""


def generate_variant_index(variants: list, summary: dict) -> str:
    """Generate an index page listing all active challenger variants."""
    variant_cards = ""
    for v in variants:
        vtype = v["variant_type"]
        variant_cards += f"""
    <div class="variant-card">
      <div class="variant-badge">{vtype.upper()}</div>
      <h3>Variant: {vtype.title()} Test</h3>
      <p class="hypothesis">{v.get('hypothesis', 'No hypothesis set')}</p>
      <p class="rationale">{v.get('rationale', '')}</p>
      <a href="{vtype}/" class="btn-view">View Variant →</a>
    </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CouponSnap CRO Challengers — LoopLab Auto-Research</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1f2937; }}
    h1 {{ font-size: 2rem; margin-bottom: 0.5rem; }}
    .meta {{ color: #6b7280; font-size: 0.9rem; margin-bottom: 2rem; }}
    .variants-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 1.5rem; }}
    .variant-card {{ border: 1px solid #e5e7eb; border-radius: 12px; padding: 1.5rem; }}
    .variant-badge {{ display: inline-block; background: #2563eb; color: white; padding: 0.2rem 0.7rem; border-radius: 20px; font-size: 0.75rem; font-weight: 700; margin-bottom: 0.75rem; }}
    h3 {{ font-size: 1.1rem; margin-bottom: 0.5rem; }}
    .hypothesis {{ font-size: 0.9rem; color: #374151; background: #f0fdf4; border-left: 3px solid #10b981; padding: 0.75rem; border-radius: 4px; margin: 0.75rem 0; }}
    .rationale {{ font-size: 0.85rem; color: #6b7280; }}
    .btn-view {{ display: inline-block; margin-top: 1rem; background: #2563eb; color: white; padding: 0.5rem 1.2rem; border-radius: 6px; text-decoration: none; font-size: 0.9rem; font-weight: 600; }}
    .pipeline-info {{ background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 1.5rem; margin-bottom: 2rem; }}
    .pipeline-info h2 {{ font-size: 1.1rem; margin-bottom: 0.5rem; }}
  </style>
</head>
<body>
  <h1>🔬 CouponSnap CRO Challengers</h1>
  <p class="meta">Generated by LoopLab Auto-Research Pipeline · {summary.get('generated_at', '')[:10]} · Base: <a href="{GITHUB_PAGES_BASE}">{GITHUB_PAGES_BASE}</a></p>

  <div class="pipeline-info">
    <h2>Pipeline: Karpathy Auto-Research Pattern</h2>
    <p>Harvest → Evaluate → Generate → Deploy → Log</p>
    <p>Each variant tests one isolated hypothesis. GA4 tracks conversion events per variant for data-driven winner selection.</p>
  </div>

  <div class="variants-grid">
{variant_cards}
  </div>
</body>
</html>"""


def create_deployment_manifest(variants: list, summary: dict) -> dict:
    """Create deployment manifest for tracking active experiments."""
    return {
        "deployment_id": f"deploy_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}",
        "deployed_at": datetime.utcnow().isoformat() + "Z",
        "base_url": f"{GITHUB_PAGES_BASE}/",
        "control_url": f"{GITHUB_PAGES_BASE}/",
        "challengers": [
            {
                "variant_id": v.get("variant_id", f"v_{v['variant_type']}"),
                "variant_type": v["variant_type"],
                "url": f"{GITHUB_PAGES_BASE}/challengers/{v['variant_type']}/",
                "hypothesis": v.get("hypothesis", ""),
                "status": "active",
                "deployed_at": datetime.utcnow().isoformat() + "Z",
            }
            for v in variants
        ],
        "ga4_events_to_track": [
            "cta_click",
            "how_it_works_click",
            "blog_click",
            "variant_view",
        ],
        "success_metric": "cta_click (chrome webstore)",
        "run_duration_days": 7,
    }


def main():
    import sys

    # Check if called with --generate-index flag (from GitHub Actions)
    generate_index_only = "--generate-index" in sys.argv

    summary = load_variants_summary()
    variants = summary.get("variants", [])

    if not variants:
        print("[deploy] No variants found in summary. Run generate.py first.")
        return

    # Create challengers directory structure
    challengers_dir = REPO_ROOT / "challengers"
    challengers_dir.mkdir(exist_ok=True)

    if not generate_index_only:
        # Generate GitHub Actions workflow
        workflow_dir = REPO_ROOT / ".github" / "workflows"
        workflow_dir.mkdir(parents=True, exist_ok=True)
        workflow_path = workflow_dir / "deploy-challengers.yml"
        workflow_content = generate_github_actions_workflow(variants)
        with open(workflow_path, "w", encoding="utf-8") as f:
            f.write(workflow_content)
        print(f"[deploy] GitHub Actions workflow → {workflow_path}")

    # Generate variant index page
    index_html = generate_variant_index(variants, summary)
    index_path = challengers_dir / "index.html"
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_html)
    print(f"[deploy] Variant index page → {index_path}")

    # Create deployment manifest
    manifest = create_deployment_manifest(variants, summary)
    manifest_path = challengers_dir / "manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    print(f"[deploy] Deployment manifest → {manifest_path}")

    if not generate_index_only:
        # Save deployment record
        deploy_record_path = DATA_DIR / "deployment.json"
        with open(deploy_record_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, ensure_ascii=False, indent=2)

        print(f"\n[deploy] Deployment ready!")
        print(f"[deploy] Control:    {GITHUB_PAGES_BASE}/")
        for c in manifest["challengers"]:
            print(f"[deploy] Challenger: {c['url']}")
        print(f"\n[deploy] Next: commit + push to trigger GitHub Actions workflow")
        print(f"[deploy]   git add -A && git commit -m 'chore: CRO challengers deploy'")
        print(f"[deploy]   git push")

    return manifest


if __name__ == "__main__":
    main()
